### ISSUE TITLE
tsconfig.json references an external file

### ISSUE THREAD

**Issue by francescopellegrini** [99xt/cognito-jwt-token-validator#1]
Visual Studio Code complains that [tsconfig.json](https://github.com/99xt/cognito-jwt-token-validator/blob/master/tsconfig.json#L2) extends a non-existing file: gts is a [dev-only dependency](https://github.com/99xt/cognito-jwt-token-validator/blob/master/package.json#L35) so it gets not resolved in my project.

**Comment by AshanFernando** [comment]
@francescopellegrini Thanks for reporting the issue. Will you be able to send a PR removing the file reference?

**Comment by francescopellegrini** [comment]
@AshanFernando did you see my PR?

**Comment by AshanFernando** [comment]
@francescopellegrini Merged the PR. Thanks @francescopellegrini
